// Import Sequelize to define the data base table.
import { Sequelize } from "sequelize";
// Import the database connection.
import db from '../config/database.js';

// Data types that sequelize recognizes to define the table columns data types.
const {DataTypes} = Sequelize;

// Data base table definition City.
var City= db.define('city', {
    id:{
        type:DataTypes.INTEGER
        ,autoIncrement:true 
  
        ,allowNull:false, 
  
        primaryKey:true
    }
    ,name:{
        type: DataTypes.STRING
    }
    ,state:{
        type: DataTypes.STRING
    }
    ,km2:{
        type: DataTypes.INTEGER
    }
}
,{
    // Removes the autogenerated timestamps from sequelize.
    timestamps: false
    // Stops sequelize from pluralizing the table names.
    ,freezeTableName: true
});

// Syncs the database to create the table based on the model.
await db.sync()

// Exports the class so it can be used in other classes.
export default City;